name: Cargo Build & Test
on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_INCREMENTAL: 0

jobs:
  build_and_test:
    name: Bittorrent Rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo build --verbose
      - run: cargo test --verbose
